{% set name = "openmim" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmim-{{ version }}.tar.gz
  sha256: 42758b68fa6288bea5e70f0ef63b8c872f1d620b5e4e43c52d93dac54e70fb2e

build:
  entry_points:
    - mim = mim.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - colorama
    - model-index
    - pandas
    - pip >=19.3
    - requests
    - rich
    - tabulate

test:
  source_files:
    - tests
  imports:
    - mim
  commands:
    - pip check
    - mim --help
    - pytest tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/open-mmlab/mim
  summary: MIM Installs OpenMMLab packages
  description: |
    MIM provides a unified interface for launching and installing OpenMMLab projects and their extensions, and managing
    the OpenMMLab model zoo.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://github.com/open-mmlab/mim
  dev_url: https://github.com/open-mmlab/mim

extra:
  recipe-maintainers:
    - zhouzaida
    - giswqs
