{% set name = "openmim" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmim-{{ version }}.tar.gz
  sha256: ce42fd018f5db27c5c9f79a6795afd980ade28acf0f0f39cf1abdc961573dab6

build:
  entry_points:
    - mim = mim.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - colorama
    - model-index
    - pandas
    - pip >=19.3
    - requests
    - rich
    - tabulate

test:
  imports:
    - mim
  commands:
    - pip check
    - mim --help
  requires:
    - pip

about:
  home: https://github.com/open-mmlab/mim
  summary: MIM Installs OpenMMLab packages
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zhouzaida
    - giswqs
